version: '3'
services:
  voyager:
    build:
      context: '${BACK_END}'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
        - 'BACK_END=${BACK_END}'
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'XDEBUG=${XDEBUG}'
        - 'LARAVEL_VERSION=${LARAVEL_VERSION}'
        - 'INSTALL_ADDITIONAL_EXTENSIONS=${INSTALL_ADDITIONAL_EXTENSIONS}'
        - 'DB_NAME=${DB_NAME}'
        - 'DB_USER=${DB_USER}'
        - 'DB_PASSWORD=${DB_PASSWORD}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_VOYAGER}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${VOYAGER_HOST_HTTP_PORT}:80'
  mysql:
    image: mariadb:10.5
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
volumes: {}
