version: '3.7'
 
services:
  app:
    build: 
      context: ./voyager
    ports:
      - ${VOYAGER_PORT}:80
    volumes:
      - ${APP_CODE_PATH_HOST}:/app

  mysql:
    image: mysql:5.7.27
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data

volumes:
  db_data:
